### ISSUE TITLE
ToC does not correspond to document structure

### ISSUE THREAD

**Issue by gerr135** [ohenley/readme-template#1]
Hi Olivier,

Thank you for preparing a nice looking Readme template.
I am actually trying to use it, as you see :) (for my ada_gems project right now, to be renamed as we discussed in its own issue). 

I just wanted to point out a small, well, issue with your template. You provide a subsection code for the Table of Contents with clickable references (e.g. (#about), etc..). But none of the references correspond to any of the actual hashed (sub)headings. This is quite disorienting, especially since you do have multiple headings in the text. I understand the intention of the provided ToC code - to suggest most common structure. But when it does not reference your own document, it may confuse people (even if for all of 1 min) into thinking those references are something special and not merely #Subheading text.. So, I think your ToC code should include at least your own #*subsection references and, ideally, a short comment on how it all links together at some point (separate HowTo/Readme if you think it has no place in main one?).

Thanks again for your effort!

George

**Comment by ohenley** [comment]
Thx for the pointer. It is fixed.

ps: I will get back to you (email) ASAP, but now my plate is full with the job. ;)

**Comment by gerr135** [comment]
Thanks, that was quick!

PS
Sure, no worries, I totally on board with that one. I myself just finally had a bit of time and inspiration to start updating the Readme there :).
